# Generated by Django 4.1.4 on 2023-01-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_story_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='date_posted',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='summary',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
